version: '3.8'

services:
    ratings:
        build: .
        ports:
            - "8099:8080"
        environment: 
            SERVICE_VERSION: v2

    mongodb:
        image: bitnami/mongodb:4.4.2-debian-10-r0
        volumes:
            - "./databases:/docker-entrypoint-initdb.d.sh"